/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package swingGUI;

import common.ServiceFailureException;
import hotelmanager.Parser;
import hotelmanager.Person;
import java.io.IOException;
import java.util.Locale;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.SwingWorker;

/**
 *
 * @author Cmato
 */
public class AddPerson extends javax.swing.JFrame {

    private ResourceBundle general = HotelManagerFrame.LANGUAGE;
    private Long updatePersonId;
    private Person originalPerson;
	    
    /**
     * Creates new form AddPerson
     */
    public AddPerson() {
	initComponents();
	updatePersonId = null;
    }
    
    public AddPerson(String updatePerson) {
	initComponents();
	setUpdatedPerson(updatePerson);
	addPersonButton.setText(general.getString("updatePerson"));
    }
    
    private void setUpdatedPerson(String stringPerson)
    {
	Parser parser = new Parser();
	try {
	    originalPerson = parser.parseStringToPerson(stringPerson);
	} catch (IOException e) {
	    Logger.getLogger(this.getName()).log(Level.SEVERE, null, e);
            new SetErrorMessage("<html>"+general.getString("errFormatPerson")+"</html>");
	}
	updatePersonId = originalPerson.getId();
	personName.setText(originalPerson.getName());
	personSurname.setText(originalPerson.getSurname());
	personIdCardNumber.setText(originalPerson.getIdCardNumber());
	personEmail.setText(originalPerson.getEmail());
	personMobile.setText(originalPerson.getMobile());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        personName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        personSurname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        personIdCardNumber = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        personMobile = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        personEmail = new javax.swing.JTextField();
        addPersonButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText(general.getString("name"));

        jLabel2.setText(general.getString("surname"));

        jLabel3.setText(general.getString("idCardNumber"));

        jLabel4.setText(general.getString("mobile"));

        jLabel5.setText(general.getString("email"));

        personEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personEmailActionPerformed(evt);
            }
        });

        addPersonButton.setText(general.getString("addPerson"));
        addPersonButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addPersonButtonMouseClicked(evt);
            }
        });

        jButton2.setText(general.getString("cancel"));
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(personSurname, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(personIdCardNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(personName, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(personEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                                .addComponent(personMobile)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(addPersonButton)))
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(personName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(personSurname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(personIdCardNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(personMobile, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(personEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addPersonButton)
                    .addComponent(jButton2))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void personEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personEmailActionPerformed
	// TODO add your handling code here:
    }//GEN-LAST:event_personEmailActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
	this.setVisible(false);
    }//GEN-LAST:event_jButton2MouseClicked

    private void addPersonButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addPersonButtonMouseClicked
	new SwingWorker<Void, Void>() {
            Person tmpPerson = new Person();
            @Override
            protected Void doInBackground(){
                
		tmpPerson.setName(personName.getText());
		tmpPerson.setSurname(personSurname.getText());
		tmpPerson.setEmail(personEmail.getText());
		tmpPerson.setIdCardNumber(personIdCardNumber.getText());
		tmpPerson.setMobile(personMobile.getText());
		
                try {
		    if(updatePersonId != null)
		    {
			tmpPerson.setId(updatePersonId);
			HotelManagerFrame.getPersonManager().updatePerson(tmpPerson);
			HotelManagerFrame.getPersonListModel().removePerson(originalPerson);
			HotelManagerFrame.getPersonCheckListModel().removePerson(originalPerson);
			Logger.getLogger(AddPerson.this.getName()).log(Level.INFO, "Successfuly updated person.");
		    } else{
			HotelManagerFrame.getPersonManager().createPerson(tmpPerson);
			Logger.getLogger(AddPerson.this.getName()).log(Level.INFO, "Successfuly created person.");
		    }
		    
                    HotelManagerFrame.getPersonListModel().addPerson(tmpPerson);
		    HotelManagerFrame.getPersonCheckListModel().addPerson(tmpPerson);
		    
		    AddPerson.this.setVisible(false);
		    
                    return null;
		    
                } catch (ServiceFailureException e) {
                    Logger.getLogger(AddPerson.this.getName()).log(Level.SEVERE, null, e);
                    new SetErrorMessage("<html>"+general.getString("errReqFields")+"</html>");
                }
                return null;
            }

            @Override
            protected void done() {
                
            }
        }.execute();
    }//GEN-LAST:event_addPersonButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
	/*
	 * Set the Nimbus look and feel
	 */
	//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
	 * If Nimbus (introduced in Java SE 6) is not available, stay with the
	 * default look and feel. For details see
	 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
	 */
	try {
	    for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
		if ("Nimbus".equals(info.getName())) {
		    javax.swing.UIManager.setLookAndFeel(info.getClassName());
		    break;
		}
	    }
	} catch (ClassNotFoundException ex) {
	    java.util.logging.Logger.getLogger(AddPerson.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (InstantiationException ex) {
	    java.util.logging.Logger.getLogger(AddPerson.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (IllegalAccessException ex) {
	    java.util.logging.Logger.getLogger(AddPerson.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (javax.swing.UnsupportedLookAndFeelException ex) {
	    java.util.logging.Logger.getLogger(AddPerson.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	}
	//</editor-fold>

	/*
	 * Create and display the form
	 */
	java.awt.EventQueue.invokeLater(new Runnable() {

	    public void run() {
		//new AddPerson().setVisible(true);
	    }
	});
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addPersonButton;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField personEmail;
    private javax.swing.JTextField personIdCardNumber;
    private javax.swing.JTextField personMobile;
    private javax.swing.JTextField personName;
    private javax.swing.JTextField personSurname;
    // End of variables declaration//GEN-END:variables
}
