/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package swingGUI;

import common.ServiceFailureException;
import hotelmanager.Parser;
import hotelmanager.Person;
import hotelmanager.Room;
import hotelmanager.RoomType;
import java.io.IOException;
import java.util.Locale;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.SwingWorker;

public class RemoveItem extends javax.swing.JFrame {

    private ResourceBundle general = HotelManagerFrame.LANGUAGE;
    private Person removePerson;
    private Room removeRoom;
    private boolean isPerson;
    /**
     * Creates new form RemoveItem
     */
    public RemoveItem(boolean isPerson, String removeItem) {
	this.isPerson = isPerson;
	parseInput(isPerson, removeItem);
	initComponents();
	removeMessage.setText("<html>"+general.getString("messRemoveItem")+"<br /><br />     "+removeItem+"</html>");
    }

    private void parseInput(boolean isPerson, String removeItem)
    {
	Parser parser = new Parser();
	if(isPerson)
	{
	    try{
		removePerson = parser.parseStringToPerson(removeItem);
	    } catch (IOException e) {
		Logger.getLogger(this.getName()).log(Level.SEVERE, null, e);
		new SetErrorMessage("<html>"+general.getString("errFormatPerson")+" </html>");
	    }
	}
	else
	{
	    try{
		removeRoom = parser.parseStringToRoom(removeItem);
	    } catch (IOException e) {
		Logger.getLogger(this.getName()).log(Level.SEVERE, null, e);
		new SetErrorMessage("<html>"+general.getString("errFormatRoom")+" </html>");
	    }
	}
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        removeMessage = new javax.swing.JLabel();
        removeButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        removeButton.setText(general.getString("remove"));
        removeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                removeButtonMouseClicked(evt);
            }
        });

        jButton2.setText(general.getString("cancel"));
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(removeMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(removeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(removeMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(removeButton))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
	this.setVisible(false);
    }//GEN-LAST:event_jButton2MouseClicked

    private void removeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeButtonMouseClicked
	new SwingWorker<Void, Void>() {
            @Override
            protected Void doInBackground(){
                try {
		    if(isPerson)
		    {
			HotelManagerFrame.getPersonManager().deletePerson(removePerson);
			HotelManagerFrame.getPersonListModel().removePerson(removePerson);
			HotelManagerFrame.getPersonCheckListModel().removePerson(removePerson);
			Logger.getLogger(RemoveItem.this.getName()).log(Level.INFO, "Successfuly removed person.");
		    } else{
			HotelManagerFrame.getRoomManager().deleteRoom(removeRoom);
			HotelManagerFrame.getRoomListModel().removeRoom(removeRoom);
			HotelManagerFrame.getRoomUpdateRemoveListModel().removeRoom(removeRoom);
			Logger.getLogger(RemoveItem.this.getName()).log(Level.INFO, "Successfuly removed room.");
		    }
		    
		    RemoveItem.this.setVisible(false);
		    
                    return null;
		    
                } catch (ServiceFailureException e) {
                    Logger.getLogger(RemoveItem.this.getName()).log(Level.SEVERE, null, e);
                    new SetErrorMessage("<html>"+general.getString("errDelPersonRoom")+" </html>");
                }
                return null;
            }

            @Override
            protected void done() {
                
            }
        }.execute();
    }//GEN-LAST:event_removeButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
	/*
	 * Set the Nimbus look and feel
	 */
	//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
	 * If Nimbus (introduced in Java SE 6) is not available, stay with the
	 * default look and feel. For details see
	 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
	 */
	try {
	    for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
		if ("Nimbus".equals(info.getName())) {
		    javax.swing.UIManager.setLookAndFeel(info.getClassName());
		    break;
		}
	    }
	} catch (ClassNotFoundException ex) {
	    java.util.logging.Logger.getLogger(RemoveItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (InstantiationException ex) {
	    java.util.logging.Logger.getLogger(RemoveItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (IllegalAccessException ex) {
	    java.util.logging.Logger.getLogger(RemoveItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (javax.swing.UnsupportedLookAndFeelException ex) {
	    java.util.logging.Logger.getLogger(RemoveItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	}
	//</editor-fold>

	/*
	 * Create and display the form
	 */
	java.awt.EventQueue.invokeLater(new Runnable() {

	    public void run() {
		
	    }
	});
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton removeButton;
    private javax.swing.JLabel removeMessage;
    // End of variables declaration//GEN-END:variables
}
