CREATE TABLE PERSON (
        ID INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
        NAME VARCHAR(255),
        SURNAME VARCHAR(255),
        idCardNumber VARCHAR(255),
        mobile VARCHAR(255),
        email VARCHAR(255)
 );

CREATE TABLE ROOM (
        ID INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
        TYPE VARCHAR(255),
        CAPACITY INTEGER
 );