CREATE TABLE "ROOM" (
        "ID" BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
        "TYPE" VARCHAR(255),
        "CAPACITY" INTEGER NOT NULL
 );

CREATE TABLE "PERSON" (
        "ID" BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	"ROOMID" BIGINT REFERENCES ROOM (ID),
        "NAME" VARCHAR(255),
        "SURNAME" VARCHAR(255),
        "IDCARDNUMBER" VARCHAR(255),
        "MOBILE" VARCHAR(255),
        "EMAIL" VARCHAR(255)
 );